name: Daily Stock Report Update
on:
  schedule:
    - cron: '0 23,7,14 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 이 줄이 마스터키를 사용하는 핵심입니다!
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pandas requests beautifulsoup4 yfinance
      - run: python update_report.py
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Automated update" || true
          git push origin main
