name: Daily Stock Report Update
on:
  schedule:
    - cron: '0 23,7,14 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 깃허브가 스스로 파일을 수정할 수 있도록 허락(프리패스)하는 핵심 코드!
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install pandas requests beautifulsoup4 yfinance
      - run: python update_report.py
      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Automated report update" || true
          git push origin main
